### ISSUE TITLE
[Discussion: feature] Add a search cache key functionality

### ISSUE THREAD

**Issue by cglacet** [razorpay/react-native-apollo-devtools#20]
The plugin works well on the most recent version of flipper (173.0) but it seems like there is no way to find a given key in the cache. I don't have a very large cache data structure (less than 100 keys) but it's already very hard to find a key in all that mess. 

I'm not sure my use case is representative but I usually 1) find a cache entry that has an issue, 2) find the reference that is not updated correctly if there is one or proceed to the sub-field. During this process I'll usually need to search for a few keys (which used to be instantaneous with the old methods ([RN debugger](https://github.com/jhen0409/react-native-debugger)) since they had this search mechanism (if I remember correctly they even had links on cache references).

To me that the most important feature that is missing to make this plugin usable. 

Maybe a quick fix would be to sort keys alphabetically. 

Thanks for your work on this important plugin!

**Comment by schonarth** [comment]
I couldn't agree more.

I'm in a large project and it's virtually impossible to find any specific key I'm looking for. Fortunately the plugin is very snappy so it's easy to look up and down even with relatively large amounts of data, and so far I've only needed to check that entries of certain types are making it (or not) into the cache, but finer navigation is a challenge.

A search feature or (maybe optional) sorting of the keys would make a huge quality-of-like improvement!

**Comment by mohit23x** [comment]
I agree, the search feature has been on our roadmap since the start, and we'll try to accommodate it in future versions of the tool.

**Comment by mohit23x** [comment]
Thanks to @paullbn the Search feature is available in version 1.2.0, do update your flipper plugins.
